server:
    port: 8080

spring:
    data:
      mongodb:
          host: emailserverstub_email-db_1
          port: 27017
          database: emails

    mail:
      host: emailserverstub_email-server_1
      port: 25000
      send.from: sendfrom@example.com
